<a href="https://colab.research.google.com/github/Anurag-Singla/colab/blob/main/TensorFlow_2_Basics_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow 2 Exercises for Basic Tensor Manipulation

This notebook provides a set of exercises designed to familiarize you with the basics of tensor manipulation in TensorFlow 2,
which is essential for handling Large Language Models (LLMs).

## Contents
1. Tensor Basics
2. Tensor Operations
3. Manipulating Tensor Shapes
4. Indexing and Slicing

Each section will include a brief explanation followed by practical exercises.


## 1. Tensor Basics

**Objective**: Understand how to create tensors, and learn about their types and shapes.

**Exercises**:
1. Create a scalar tensor (0-D tensor) with a specific value.
2. Create a 1-D tensor (vector) with 5 elements.
3. Create a 2-D tensor (matrix) of shape (3, 3).
4. Find the data type (`dtype`) of the tensors created above.
5. Convert a numpy array to a TensorFlow tensor.



## 2. Tensor Operations

**Objective**: Perform basic arithmetic operations and learn some advanced operations.

**Exercises**:
1. Add, subtract, multiply, and divide two tensors.
2. Compute the mean and standard deviation of a tensor.
3. Apply a non-linear activation function (like ReLU) to a tensor.
4. Perform matrix multiplication between two 2-D tensors.



## 3. Manipulating Tensor Shapes

**Objective**: Learn how to reshape and transpose tensors.

**Exercises**:
1. Create a tensor of shape (4, 4), then reshape it to (2, 8).
2. Transpose a 2-D tensor.
3. Flatten a 3-D tensor to a 1-D tensor.



## 4. Indexing and Slicing

**Objective**: Access specific elements or slices of a tensor.

**Exercises**:
1. Extract a specific element from a tensor.
2. Slice a portion of a tensor.
3. Use boolean tensor indexing to filter elements.


In [1]:
import tensorflow as tf
import numpy as np

scalar = tf.constant(2)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [2]:
# prompt: Create a scalar tensor (0-D tensor) with a specific value.
# Create a 1-D tensor (vector) with 5 elements.
# Create a 2-D tensor (matrix) of shape (3, 3).
# Find the data type (dtype) of the tensors created above.
# Convert a numpy array to a TensorFlow tensor.

vector = tf.constant([1, 2, 3, 4, 5])
vector
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix
print(scalar.dtype)
print(vector.dtype)
print(matrix.dtype)
numpy_array = np.array([10, 20, 30])
tensor_from_numpy = tf.convert_to_tensor(numpy_array)
tensor_from_numpy

<dtype: 'int32'>
<dtype: 'int32'>
<dtype: 'int32'>


<tf.Tensor: shape=(3,), dtype=int64, numpy=array([10, 20, 30])>

In [14]:
"""
2. Tensor Operations
Objective: Perform basic arithmetic operations and learn some advanced operations.

Exercises:

Add, subtract, multiply, and divide two tensors.
Compute the mean and standard deviation of a tensor.
"""

tensor1 = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
tensor2 = tf.constant([6, 7, 8, 9, 10], dtype=tf.float32)

print(tensor1 + tensor2)
print(tensor1 - tensor2)
print(tensor1 * tensor2)
print(tensor1 / tensor2)

print(tf.reduce_mean(tensor1))
print(tf.math.reduce_std(tf.cast(tensor1, dtype=tf.float32)))
print(tf.math.reduce_std(tensor1))




tf.Tensor([ 7.  9. 11. 13. 15.], shape=(5,), dtype=float32)
tf.Tensor([-5. -5. -5. -5. -5.], shape=(5,), dtype=float32)
tf.Tensor([ 6. 14. 24. 36. 50.], shape=(5,), dtype=float32)
tf.Tensor([0.16666667 0.2857143  0.375      0.44444445 0.5       ], shape=(5,), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(1.4142135, shape=(), dtype=float32)
tf.Tensor(1.4142135, shape=(), dtype=float32)


In [5]:
# Apply a non-linear activation function (like ReLU) to a tensor.
relu_tensor = tf.constant([-1, 0, 1, 2, -2])
relu_output = tf.nn.relu(relu_tensor)
print(relu_output)

tf.Tensor([0 0 1 2 0], shape=(5,), dtype=int32)


In [7]:
# Perform matrix multiplication between two 2-D tensors with dimensions 3x2 and 2x5.
matrix_a = tf.constant([[1, 2], [3, 4], [5, 6]]) # Shape (3, 2)
matrix_b = tf.constant([[7, 8, 9, 10, 11], [12, 13, 14, 15, 16]]) # Shape (2, 5)

matrix_c = tf.matmul(matrix_a, matrix_b)
print(matrix_c)

tf.Tensor(
[[ 31  34  37  40  43]
 [ 69  76  83  90  97]
 [107 118 129 140 151]], shape=(3, 5), dtype=int32)


In [8]:
# Create a tensor of shape (4, 4), then reshape it to (2, 8).
tensor_4x4 = tf.constant([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12],
                           [13, 14, 15, 16]])
reshaped_tensor = tf.reshape(tensor_4x4, (2, 8))
print("Original tensor (4x4):")
print(tensor_4x4)
print("\nReshaped tensor (2x8):")
print(reshaped_tensor)

Original tensor (4x4):
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]], shape=(4, 4), dtype=int32)

Reshaped tensor (2x8):
tf.Tensor(
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]], shape=(2, 8), dtype=int32)


In [10]:
# Transpose a 2-D tensor.
tensor_2d = tf.constant([[1, 2, 3],
                           [4, 5, 6]])
transposed_tensor = tf.transpose(tensor_2d)
print("Original tensor (2D):")
print(tensor_2d)
print("\nTransposed tensor:")
print(transposed_tensor)

Original tensor (2D):
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Transposed tensor:
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [20]:
# Flatten a 3-D tensor to a 1-D tensor.
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
flattened_tensor = tf.reshape(tensor_3d, [-1])
print("Original tensor (3D):")
print(tensor_3d)
print("\nFlattened tensor (1D):")
print(flattened_tensor)

Original tensor (3D):
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)

Flattened tensor (1D):
tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)


In [15]:
# Extract a specific element from a tensor.
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = tensor[1, 2] # Access element at row 1, column 2 (0-indexed)
print("Original tensor:")
print(tensor)
print("\nExtracted element (tensor[1, 2]):")
print(element)

Original tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

Extracted element (tensor[1, 2]):
tf.Tensor(6, shape=(), dtype=int32)


In [16]:
# Slice a portion of a tensor.
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sliced_tensor = tensor[:, 1:3] # Slice all rows, columns from index 1 up to (but not including) 3
print("Original tensor:")
print(tensor)
print("\nSliced tensor (tensor[:, 1:3]):")
print(sliced_tensor)

Original tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

Sliced tensor (tensor[:, 1:3]):
tf.Tensor(
[[2 3]
 [5 6]
 [8 9]], shape=(3, 2), dtype=int32)


In [17]:
# Use boolean tensor indexing to filter elements.
tensor = tf.constant([10, 20, 30, 40, 50, 60])
boolean_mask = tensor > 30 # Create a boolean tensor
filtered_tensor = tensor[boolean_mask] # Use the boolean tensor to filter
print("Original tensor:")
print(tensor)
print("\nBoolean mask (tensor > 30):")
print(boolean_mask)
print("\nFiltered tensor:")
print(filtered_tensor)

Original tensor:
tf.Tensor([10 20 30 40 50 60], shape=(6,), dtype=int32)

Boolean mask (tensor > 30):
tf.Tensor([False False False  True  True  True], shape=(6,), dtype=bool)

Filtered tensor:
tf.Tensor([40 50 60], shape=(3,), dtype=int32)
